// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Versatus.ForcaVendas.Infrastructure.Data;

#nullable disable

namespace Versatus.ForcaVendas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    partial class PedidosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("TotalBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pedido_itens", (string)null);
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoParcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pedido_parcelas", (string)null);
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("pedido_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "rascunho",
                            Descricao = "Rascunho"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "enviado",
                            Descricao = "Enviado"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "processado",
                            Descricao = "Processado"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "erro",
                            Descricao = "Erro"
                        });
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Infrastructure.Data.SessionAuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Infrastructure.Data.TenantSubscriptionEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_empresa");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("MaxConcurrentUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_usuarios_simultaneos");

                    b.HasKey("TenantId");

                    b.ToTable("assinaturas", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CompanyName = "Demo Tenant 1",
                            IsActive = true,
                            MaxConcurrentUsers = 4
                        },
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CompanyName = "Demo Tenant 2",
                            IsActive = true,
                            MaxConcurrentUsers = 4
                        });
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Infrastructure.Data.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c90e66f-0af5-4ded-90e2-0df0a0b2d001"),
                            Ativo = true,
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 4, 12, 16, 7, 19, 627, DateTimeKind.Unspecified).AddTicks(5015), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$ciSTyOS/P1XmbUlSxGlhaeKggvqND4mOTYTakRxHtm52LS/kJclmO",
                            Role = "admin",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("7c90e66f-0af5-4ded-90e2-0df0a0b2d002"),
                            Ativo = true,
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 4, 12, 16, 7, 19, 627, DateTimeKind.Unspecified).AddTicks(5025), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$ciSTyOS/P1XmbUlSxGlhaeKggvqND4mOTYTakRxHtm52LS/kJclmO",
                            Role = "gestor",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Username = "gestor"
                        });
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.Pedido", b =>
                {
                    b.HasOne("Versatus.ForcaVendas.Domain.Pedidos.PedidoStatus", "Status")
                        .WithMany("Pedidos")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoItem", b =>
                {
                    b.HasOne("Versatus.ForcaVendas.Domain.Pedidos.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoParcela", b =>
                {
                    b.HasOne("Versatus.ForcaVendas.Domain.Pedidos.Pedido", "Pedido")
                        .WithMany("Parcelas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Versatus.ForcaVendas.Domain.Pedidos.PedidoStatus", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
